<h1>Matrixzerlegungen</h1>

<h2>Eigenwerte und Eigenvektoren</h2>

<font size="3" face="Verdana">
<p style="text-align:justify">Für alle quadratische Matrizen können Eigenwerte und Eigenvektoren berechnet werden. Ein Eigenvektor der Matrix $A$ ändert nicht seine Richtung, wenn er mit $A$ multipliziert wird. Er wird nur um den Wert des dazugehörigen Eigenwertes skaliert. Im Bereich Computer Vision werden Eigenwerte und Eigenvektoren unter anderem benötigt, um die Pseudoinverse einer nicht-quadratischen Matrix mittels der Singulärwertzerlegung zu bestimmen. Dies wird im Abschnitt Singulärwertzerlegung behandelt.</p>
</font>

<h2>Eigenwerte und Eigenvektoren</h2>

<font size="3" face="Verdana">
   
<p style="text-align:justify">Alle Vektoren $e$, die nicht null sind und für die es ein $\lambda \in \mathbb{R}$ gibt sodass: $Ae = \lambda e$, heißen Eigenvektoren von $A$. $\lambda$ ist der dazugehörige Eigenwert.</p>
    
<p style="text-allign:justify">Dies kann auch geschrieben werden als:</p>

\begin{align}
(A - \lambda I) e = 0
\end{align}

<p style="text-align:justify">Ist $e$ ein Eigenvektor der Matrix $A$, so ist auch $c*e, c \neq 0$ ein Eigenvektor dieser Matrix.</p>

<p style="text-align:justify">Die Eigenwerte und die dazugehörigen Eigenvektoren werden folgendermaßen benannt:</p>

\begin{align}
\lambda_1 \geq \lambda_2 \geq \dots \geq \lambda_n \\
e_1, e_2, ..., e_n
\end{align}

<p style="text-align:justify">Da $(A - \lambda I)$ den Vektor $e$ auf den Nullvektor abbildet, ist es unmöglich damit zurück auf $e$ zu schließen. Somit ist $(A- \lambda I)$ nicht invertierbar, hat also nicht vollen Rang. </p>

<p style="text-align:justify">Daher muss gelten: </p>

\begin{align}
det(A - \lambda I) = 0
\end{align}

<p style="text-align:justify">Diese Determinante wird auch als "charakteristisches Polynom" bezeichnet. Es hat die Form $\lambda^n + \alpha_{n-1}*\lambda^{n-1} + \dots + \alpha_1*\lambda+\alpha_0 = 0$. Das Berechnen der Nullstellen liefert die Eigenwerte.</p>

<p style="text-align:justify">Sind die Eigenwerte bekannt, können die Eigenvektoren berechnet werden, indem für jeden Eigenwert das folgende Gleichungssystem gelöst wird:</p>

\begin{align}
(A - \lambda I) e = 0
\end{align}

</font>

<h2>Beispiel 1: Eigenwerte und Eigenvektoren berechnen</h2>

<font size="3" face="Verdana">
<p style="text-align:justify">Berechne die Eigenwerte und Eigenvektoren der Matrix:</p>
  
\begin{align}
A = 
\begin{bmatrix} 
    5 & -2 \\
    6 & -2 
\end{bmatrix}
\end{align}

<p style="text-align:justify">Verwende die Determinante um die Eigenwerte zu bestimmen:</p>

\begin{align}
det(A - \lambda I) = 0
\end{align}

\begin{align}
det(
\begin{bmatrix} 
    5 - \lambda & -2 \\
    6 & -2 - \lambda 
\end{bmatrix})
= 0
\end{align}

\begin{align}
(5 - \lambda) * (-2 - \lambda) - (-2) * 6 = 0 \\
\lambda^2 - 3 \lambda + 2 = 0 
\end{align}

<p style="text-align:justify">Somit lauten die Eigenwerte:</p>

\begin{align}
\lambda_1 = 2 \\
\lambda_2 = 1
\end{align}

<p style="text-align:justify">Nun können durch Einsetzen der Eigenwerte in die folgende Gleichung, die Eigenvektoren berechnete werden:</p>

\begin{align}
(A - \lambda I) e = 0
\end{align}

<p style="text-align:justify"><b>Für $\boldsymbol{\lambda_1 = 2}$:</b></p>

<p style="text-align:justify">Setze für $\lambda$ 2 ein:</p>

\begin{align}
\begin{bmatrix} 
    5-2 & -2 \\
    6 & -2-2 
\end{bmatrix} 
\begin{bmatrix} 
    x_1 \\
    x_2 
\end{bmatrix}
= 0 \\
\begin{bmatrix} 
    3 & -2 \\
    6 & -4 
\end{bmatrix} 
\begin{bmatrix} 
    x_1 \\
    x_2 
\end{bmatrix}
= 0
\end{align}

<p style="text-align:justify">Löse das Gleichungssystem:</p>

\begin{align}
3 x_1 - 2 x_2 = 0\\
6 x_1 - 4 x_2 = 0\\
\end{align}

<p style="text-align:justify">Die zwei Zeilen sind nicht linear unabhängig, daher genügt es die erste zu betrachten:</p>

\begin{align}
3 x_1 - 2 x_2 = 0\\
\frac{3}{2} x_1 - x_2 = 0 \\
\frac{3}{2} x_1 = x_2
\end{align}

<p style="text-align:justify">Die Lösung ist nicht eindeutig, daher wird $x_2 = 1$ gewählt. Somit lautet der Eigenvektor:</p>
    
\begin{align}
e_1 = 
\begin{bmatrix} 
    \frac{2}{3}\\
    1 
\end{bmatrix}
\end{align}

<p style="text-align:justify"><b>Für $\boldsymbol{\lambda_2 = 1}$:</b></p>

<p style="text-align:justify">Setze für $\lambda$ 1 ein:</p>

\begin{align}
\begin{bmatrix} 
    5-1 & -2 \\
    6 & -2-1 
\end{bmatrix} 
\begin{bmatrix} 
    x_1 \\
    x_2 
\end{bmatrix}
= 0 \\
\begin{bmatrix} 
    4 & -2 \\
    6 & -3 
\end{bmatrix} 
\begin{bmatrix} 
    x_1 \\
    x_2 
\end{bmatrix}
= 0
\end{align}

<p style="text-align:justify">Löse das Gleichungssystem:</p>

\begin{align}
4 x_1 - 2 x_2 = 0\\
6 x_1 - 3 x_2 = 0\\
\end{align}

<p style="text-align:justify">Die zwei Zeilen sind nicht linear unabhängig, daher genügt es die erste zu betrachten:</p>

\begin{align}
4 x_1 - 2 x_2 = 0\\
2 x_1 - x_2 = 0 \\
2 x_1 = x_2
\end{align}

<p style="text-align:justify">Die Lösung ist nicht eindeutig, daher wird $x_2 = 1$ gewählt. Somit lautet der Eigenvektor:</p>

\begin{align}
e_2 = 
\begin{bmatrix} 
    \frac{1}{2}\\
    1 
\end{bmatrix}
\end{align}

</font>

<h2>Beispiel 2: Eigenwerte und Eigenvektoren berechnen</h2>

<font size="3" face="Verdana">
<p style="text-align:justify">Berechne die Eigenwerte und Eigenvektoren der Matrix:</p>
    
\begin{align}
A = 
\begin{bmatrix} 
    2 & -3 & 1 \\
    3 & 1  & 3 \\
   -5 & 2  & -4
\end{bmatrix}
\end{align}

<p style="text-align:justify">Verwende die Determinante von $(A - \lambda I)$ um die Eigenwerte zu bestimmen:</p>

\begin{align}
det(
\begin{bmatrix} 
    2 - \lambda & -3           & 1 \\
    3           & 1 - \lambda  & 3 \\
   -5           & 2            & -4 - \lambda
\end{bmatrix})
= 0
\end{align}

\begin{align}
(2-\lambda)(1-\lambda)(-4-\lambda) + (-3)*3*(-5) + 1*3*2 \qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad \\
- (-5)(1-\lambda)*1 - 2*3(2-\lambda) - (-4-\lambda)3*(-3) = 0  \\\\
-8 - 2\lambda + 8\lambda + 2\lambda^2 + 4\lambda + \lambda^2 - 4\lambda^2 - \lambda^3 + 56 - 5\lambda - 12 + 6\lambda - 36 - 9\lambda = 0 \\\\
-\lambda^3 - \lambda^2 + 2\lambda = 0 \\\\
\lambda*(-\lambda^2 - \lambda +2) = 0 
\end{align}

\begin{align}
\lambda_1 = 1 \\
\lambda_2 = 0 \\
\lambda_3 = -2
\end{align}

<p style="text-align:justify">Nun können mithilfe der Eigenwerte die Eigenvektoren berechnete werden:</p>

\begin{align}
(A - \lambda I) e = 0
\end{align}

<p style="text-align:justify"><b>Für $\boldsymbol{\lambda_1 = 1}$:</b></p>

\begin{align}
\begin{bmatrix} 
    2 - 1 & -3     & 1 \\
    3     & 1 - 1  & 3 \\
   -5     & 2      & -4 - 1
\end{bmatrix}
\begin{bmatrix} 
    x_1  \\
    x_2  \\
    x_3          
\end{bmatrix}
= 0 \\
\begin{bmatrix} 
    1     & -3     & 1 \\
    3     & 0      & 3 \\
   -5     & 2      & -5
\end{bmatrix}
\begin{bmatrix} 
    x_1  \\
    x_2  \\
    x_3          
\end{bmatrix}
= 0
\end{align}

\begin{align}
& I)  & x_1   & - 3x_2 & + x_3  & = 0 \\
& II) & 3x_1  &        & + 3x_3 & = 0 \\
& III)& -5x_1 & +2x_2  & -5x_3  & = 0
\end{align}

\begin{align}
II = II-3*I: 
\end{align}
\begin{align}
& I)  & x_1   & - 3x_2 & + x_3  & = 0 \\
& II) &       &   9x_2 &        & = 0 \\
& III)& -5x_1 & +2x_2  & -5x_3  & = 0
\end{align}

\begin{align}
9x_2 = 0 \\
x_2 = 0
\end{align}

\begin{align}
x_1 -3*0 + x_3 = 0 \\
x_1 + x_3 = 0 \\
x_1 = -x_3
\end{align}

\begin{align}
e_1 = 
\begin{bmatrix} 
    -1\\
    0 \\
    1 
\end{bmatrix}
\end{align}

<p style="text-align:justify"><b>Für $\boldsymbol{\lambda_2 = 0}$:</b></p>

\begin{align}
\begin{bmatrix} 
    2 - 0 & -3     & 1 \\
    3     & 1 - 0  & 3 \\
   -5     & 2      & -4 - 0
\end{bmatrix}
\begin{bmatrix} 
    x_1  \\
    x_2  \\
    x_3          
\end{bmatrix}
= 0 \\
\begin{bmatrix} 
    2     & -3     & 1 \\
    3     & 1      & 3 \\
   -5     & 2      & -4
\end{bmatrix}
\begin{bmatrix} 
    x_1  \\
    x_2  \\
    x_3          
\end{bmatrix}
= 0
\end{align}

\begin{align}
& I)  & 2x_1  & - 3x_2 & + x_3  & = 0 \\
& II) & 3x_1  & +x_2   & + 3x_3 & = 0 \\
& III)& -5x_1 & +2x_2  & -4x_3  & = 0
\end{align}

\begin{align}
I = I/2:
\end{align}
\begin{align}
& I)  & 1x_1   &- \frac{3}{2}x_2  & + \frac{1}{2}x_3  & = 0 \\
& II) & 3x_1   & +x_2             & + 3x_3            & = 0 \\
& III)& -5x_1  & +2x_2            & -4x_3             & = 0
\end{align}

\begin{align}
II = II-3I: \\
III= III+5I:
\end{align}
\begin{align}
& I)  & 1x_1   &- \frac{3}{2}x_2  & + \frac{1}{2}x_3  & = 0 \\
& II) &        & +\frac{11}{2}x_2 & + \frac{3}{2}x_3  & = 0 \\
& III)&        & -\frac{11}{2}x_2 & - \frac{3}{2}x_3  & = 0
\end{align}

\begin{align}
III= III+II:
\end{align}
\begin{align}
& I)  & 1x_1   &- \frac{3}{2}x_2  & + \frac{1}{2}x_3  & = 0 \\
& II) &        & +\frac{11}{2}x_2 & + \frac{3}{2}x_3  & = 0 \\
& III)&        &                  & 0                 & = 0
\end{align}

\begin{align}
I= I+\frac{3}{11}II:
\end{align}
\begin{align}
& I)  & 1x_1   &                  & + \frac{10}{11}x_3  & = 0 \\
& II) &        & +\frac{11}{2}x_2 & + \frac{3}{2}x_3    & = 0 \\
& III)&        &                  & 0                   & = 0
\end{align}

\begin{align}
& II) \frac{11}{2}x_2 + \frac{3}{2}x_3 = 0 \\
& II) \frac{11}{2}x_2 = -\frac{3}{2}x_3 \\
& II) x_2 = -\frac{3}{11}x_3
\end{align}

\begin{align}
& I) x_1 + \frac{10}{11}x_3 = 0 \\
& I) x_1 = - \frac{10}{11}x_3 
\end{align}

\begin{align}
e_2 = 
\begin{bmatrix} 
    - \frac{10}{11}\\
    -\frac{3}{11} \\
    1 
\end{bmatrix}
\end{align}

<p style="text-align:justify"><b>Für $\boldsymbol{\lambda_3 = -2}$:</b></p>

\begin{align}
\begin{bmatrix} 
    2 - (-2) & -3        & 1 \\
    3        & 1 - (-2)  & 3 \\
   -5        & 2         & -4 - (-2)
\end{bmatrix}
\begin{bmatrix} 
    x_1  \\
    x_2  \\
    x_3          
\end{bmatrix}
= 0 \\
\begin{bmatrix} 
    4     & -3     & 1 \\
    3     & 3      & 3 \\
   -5     & 2      & -2
\end{bmatrix}
\begin{bmatrix} 
    x_1  \\
    x_2  \\
    x_3          
\end{bmatrix}
= 0
\end{align}

\begin{align}
& I)  & 4x_1  & - 3x_2 & + x_3  & = 0 \\
& II) & 3x_1  & +3x_2  & + 3x_3 & = 0 \\
& III)& -5x_1 & +2x_2  & -2x_3  & = 0
\end{align}

\begin{align}
I=I/4:
\end{align}
\begin{align}
& I)  & x_1   & - \frac{3}{4}x_2 & + \frac{1}{4}x_3  & = 0 \\
& II) & 3x_1  & +3x_2  & + 3x_3  & = 0 \\
& III)& -5x_1 & +2x_2  & -2x_3   & = 0
\end{align}

\begin{align}
II=II-3I: \\
III=III+5I: 
\end{align}
\begin{align}
& I)  & x_1   & - \frac{3}{4}x_2 & + \frac{1}{4}x_3  & = 0 \\
& II) &       & +\frac{21}{4}x_2 & + \frac{9}{4}x_3  & = 0 \\
& III)&       & +\frac{7}{4}x_2  & -\frac{3}{4}x_3   & = 0
\end{align}

\begin{align}
II=II+3III:
\end{align}
\begin{align}
& I)  & x_1   & - \frac{3}{4}x_2 & + \frac{1}{4}x_3  & = 0 \\
& II) &       &                  & 0                 & = 0 \\
& III)&       & +\frac{7}{4}x_2  & -\frac{3}{4}x_3   & = 0
\end{align}

\begin{align}
I=7I-3III:
\end{align}
\begin{align}
& I)  & 7x_1   &                 & + \frac{16}{4}x_3  & = 0 \\
& III)&       & +\frac{7}{4}x_2  & -\frac{3}{4}x_3    & = 0
\end{align}

\begin{align}
& I)   7x_1  + \frac{16}{4}x_3  & = 0 \\
& I) 7x_1 = - \frac{16}{4}x_3 = 0 \\
& I) x_1 = -\frac{4}{7}x_3
\end{align}

\begin{align}
& III) -\frac{7}{4}x_2 = \frac{3}{4}x_3 \\
& III) x_2 = - \frac{3}{7}x_3
\end{align}

\begin{align}
e_3 = 
\begin{bmatrix} 
    - \frac{4}{7}\\
    -\frac{3}{7} \\
    1 
\end{bmatrix}
\end{align}

</font>


<h2>Code-Beispiel: Eigenwerte und Eigenvektoren berechnen</h2>

In [1]:
from numpy import linalg as LA

# Eingabe-Matrix, kann beliebig geändert werden
#A = [[5, -2],
#    [6, -2]]

A = [[2, -3, 1],
    [3, 1, 3],
    [-5, 2, -4]]

# Berechne Eigenwerte und Eigenvektoren
lamb, e = LA.eig(A)

# Eigenwerte und Eigenvektoren anzeigen
for i in range(len(lamb)):
    print("\u03BB",i,"=",round(lamb[i], 5))
    print("e",i,"=")
    for j in range(len(e[i])):
        print("     ",round(e[j][i]/e[len(e)-1][i],5))
    print("---------------")

λ 0 = -2.0
e 0 =
      -0.57143
      -0.42857
      1.0
---------------
λ 1 = -0.0
e 1 =
      -0.90909
      -0.27273
      1.0
---------------
λ 2 = 1.0
e 2 =
      -1.0
      0.0
      1.0
---------------


<h2>Singulärwertzerlegung</h2>

<font size="3" face="Verdana">
<p style="text-align:justify">Die Singulärwertzerlegung einer $m x n$ Matrix A ist eine Faktorisierung der Form:</p>
   
\begin{align}
A = U \Sigma V^T
\end{align}
    
<p style="text-align:justify">Hierbei ist $U$ eine unitäre $m x m$ Matrix, $V$ ist die adjungierte einer unitären $n x n$ Matrix und $\Sigma$ ist eine reelle, diagonale $m x n$ Matrix der Form:</p>

\begin{align}
\Sigma = 
\begin{bmatrix} 
    \sigma_1 &  & \\
     & \ddots & \\
     & & \sigma_{min n,m}
\end{bmatrix}
\end{align} 

<p style="text-align:justify">Dabei sind $\sigma_1 \geq \sigma_2 \geq \dots \geq \sigma_{min n,m} \geq 0$ die Singulärwerte.</p>

<p style="text-align:justify">Die Singulärwertzerlegung von $A$, kann mithilfe der Eigenwerte und Eigenvektoren von $A^TA$ berechnet werden.</p>

<p style="text-align:justify">Die Singulärwerte werden folgendermaßen aus den Eigenwerten $\lambda_1,...,\lambda_m$ von $A^TA$ oder $AA^T$ berechnet:</p>

\begin{align}
\sigma_i = \sqrt{\lambda_i}
\end{align}

<p style="text-align:justify">Die Spalten von $U$ sind die orthonormalen Eigenvektoren von $AA^T$ (Eigenvektoren der länge 1).</p>

<p style="text-align:justify">Die Spalten von $V$ sind die orthonormalen Eigenvektoren von $A^TA$ (Eigenvektoren der länge 1).<p/>

<p style="text-align:justify">Da die Vorzeichen der Eigenvektoren nicht eindeutig bestimmt sind, sollte nur entweder $U$ oder $V$ durch die Eigenvektoren berechnet werden. Die Spalten der jeweils anderen Matrix kann dann folgendermaßen berechnet werden: </p>

\begin{align}
u_i = \frac{1}{\sigma_i}Av_i \\
v_i = \frac{1}{\sigma_i}A^Tu_i
\end{align} 

<p style="text-align:justify">Die Singulärwertzerlegung ist somit auch nicht eindeutig, da sie von der Wahl der Vorzeichen für die Eigenvektoren abhängt.</p>

<p style="text-align:justify">Für $m<n$ sollte zuerst $V$ berechnet werden, für $m>n$ zuerst $U$.</p>
    
</font>

<h2>Beispiel 1: Singulärwertzerlegung einer Matrix</h2>

<font size="3" face="Verdana">
<p style="text-align:justify">Berechne die Singulärwertzerlegung der Matrix:</p>
    
\begin{align}
A = 
\begin{bmatrix} 
    1 &  1 \\
    0 & 1
\end{bmatrix}
\end{align} 

<p style="text-align:justify">Zunächst werden die Eigenwerte von $AA^T$ berechnet.</p>

\begin{align}
AA^T = 
\begin{bmatrix} 
    1 &  1 \\
    0 & 1
\end{bmatrix}
\begin{bmatrix} 
    1 &  0 \\
    1 & 1
\end{bmatrix} = 
\begin{bmatrix} 
    2 &  1 \\
    1 & 1
\end{bmatrix}
\end{align}

<p style="text-align:justify">Die Eigenwerte von $AA^T$ sind: $\lambda_1 \approx 2.61803$ und $\lambda_2 \approx 0.38197$. Durch Wurzelziehen erhält man die Singulärwerte:</p>

\begin{align}
\sigma_1 = \sqrt{\lambda_1} = \sqrt{2.61803} \approx 1.6180 \\
\sigma_2 = \sqrt{\lambda_2} = \sqrt{0.38197} \approx 0.6180
\end{align} 

<p style="text-align:justify">Dies ergibt die folgende $\Sigma$-Matrix:

\begin{align}
\Sigma = 
\begin{bmatrix} 
    1.6180 &  0 \\
    0 & 0.6180
\end{bmatrix}
\end{align}

<p style="text-align:justify">Die zwei Spalten der Matrix $U$ erhält man nun, indem man die Eigenvektoren von $AA^T$ berechnet. Die Eigenvektoren von $AA^T$sind:</p>

\begin{align}
e_1 = 
\begin{bmatrix} 
    1.6180  \\
    1 
\end{bmatrix} \\
e_2 = 
\begin{bmatrix} 
    -0.618  \\
    1 
\end{bmatrix}
\end{align}

<p style="text-align:justify">Diese müssen noch normiert werden, das heißt ihre länge muss 1 sein:</p>

\begin{align}
e_1 =
\begin{bmatrix} 
    \frac{1.6180}{\sqrt{1.6180^2+^2}}  \\
    \frac{1}{\sqrt{1.6180^2+^2}} 
\end{bmatrix} =
\begin{bmatrix} 
    0.8506  \\
    0.5257 
\end{bmatrix} \\
e_2 = 
\begin{bmatrix} 
    \frac{-0.618}{\sqrt{-0.618^2+1^2}}  \\
    \frac{1}{\sqrt{-0.618^2+1^2}} 
\end{bmatrix} =
\begin{bmatrix} 
    -0.5257  \\
    0.8506 
\end{bmatrix}
\end{align}

<p style="text-align:justify">Daraus erhält man dann die Matrix $U$:</p>

\begin{align}
U = 
\begin{bmatrix} 
    0.8506 &  -0.5257 \\
    0.5257 & 0.8506
\end{bmatrix}
\end{align}

<p style="text-align:justify">Die zwei Spalten der Matrix $V$ kann man nun folgendermaßen berechnen:</p>

\begin{align}
v_i = \frac{1}{\sigma_i}A^Tu_i
\end{align}

<p style="text-align:justify">Die erste Spalte ist also:</p>

\begin{align}
v_1 = \frac{1}{1.6180}
\begin{bmatrix} 
    1 &  0 \\
    1 & 1
\end{bmatrix}
\begin{bmatrix} 
    0.8506  \\
    0.5257 
\end{bmatrix}=
\begin{bmatrix} 
    0.5257  \\
    0.8506 
\end{bmatrix}
\end{align}

<p style="text-align:justify">Die zweite Spalte ist also:</p>

\begin{align}
v_2 = \frac{1}{0.6180}
\begin{bmatrix} 
    1 &  0 \\
    1 & 1
\end{bmatrix}
\begin{bmatrix} 
    -0.5257  \\
    0.8506 
\end{bmatrix}=
\begin{bmatrix} 
    -0.8506  \\
    0.5257 
\end{bmatrix}
\end{align}

<p style="text-align:justify">Daraus erhält man dann die Matrix $V$:</p>

\begin{align}
V = 
\begin{bmatrix} 
    0.5257 & -0.8506  \\
    0.8506 & 0.5257
\end{bmatrix}
\end{align}

<p style="text-align:justify">Somit lautet die Singulärwertzerlegung:</p>

\begin{align}
A = U * \Sigma * V^T
\end{align}

\begin{align}
A = 
\begin{bmatrix} 
    0.8506 &  -0.5257 \\
    0.5257 & 0.8506
\end{bmatrix} *
\begin{bmatrix} 
    1.6180 &  0 \\
    0 & 0.6180
\end{bmatrix} *
\begin{bmatrix} 
    0.5257 & 0.8506  \\
    -0.8506 & 0.5257
\end{bmatrix}
\end{align}

</font>

<h2>Beispiel 2: Singulärwertzerlegung einer Matrix</h2>

<font size="3" face="Verdana">
<p style="text-align:justify">Berechne die Singulärwertzerlegung der Matrix:</p>
    
\begin{align}
A = 
\begin{bmatrix} 
    2 &  1 & 5 \\
    0 & -2 & 3
\end{bmatrix}
\end{align} 

<p style="text-align:justify">Zunächst werden die Eigenwerte von $AA^T$ berechnet.</p>

\begin{align}
AA^T = 
\begin{bmatrix} 
    2 &  1 & 5 \\
    0 & -2 & 3
\end{bmatrix}
\begin{bmatrix} 
    2 &  0 \\
    1 & -2 \\
    5 &  3
\end{bmatrix} = 
\begin{bmatrix} 
    30 &  13 \\
    13 & 13
\end{bmatrix}
\end{align}

<p style="text-align:justify">Die Eigenwerte von $AA^T$ sind: $\lambda_1 \approx 37.0322$ und $\lambda_2 \approx 5.9678$. Durch Wurzelziehen erhält man die Singulärwerte:</p>

\begin{align}
\sigma_1 = \sqrt{\lambda_1} = \sqrt{37.0322} \approx 6.0854 \\
\sigma_2 = \sqrt{\lambda_2} = \sqrt{5.9678} \approx 2.4429
\end{align} 

<p style="text-align:justify">Da $A$ eine 2x3 Matrix ist, muss auch $\Sigma$ eine 2x3 Matrix sein. Daher wird die rechte Spalte mit 0 aufgefüllt. Dies ergibt die folgende $\Sigma$-Matrix:

\begin{align}
\Sigma = 
\begin{bmatrix} 
    6.0854 &  0 & 0\\
    0 & 2.4429  & 0
\end{bmatrix}
\end{align}

<p style="text-align:justify">Da $m<n$ werden zuerst die Spalten von $V$ berechnet. Die drei Spalten der Matrix $V$ erhält man, indem man die Eigenvektoren von $A^TA$ berechnet.</p>

\begin{align}
A^TA = 
\begin{bmatrix} 
    2 &  0 \\
    1 & -2 \\
    5 &  3
\end{bmatrix}
\begin{bmatrix} 
    2 &  1 & 5 \\
    0 & -2 & 3
\end{bmatrix}= 
\begin{bmatrix} 
    4 &  2  & 10 \\
    2 & 5   & -1 \\
    10  & -1 & 34
\end{bmatrix}
\end{align}

<p style="text-align:justify">Die Eigenvektoren sind:</p>

\begin{align}
e_1 = 
\begin{bmatrix} 
    0.2891  \\
    -0.0118 \\
    0.9572
\end{bmatrix} \\
e_2 = 
\begin{bmatrix} 
    0.3895  \\
    0.9149  \\
    -0.1063
\end{bmatrix} \\
e_2 = 
\begin{bmatrix} 
    -0.8744  \\
    0.4036 \\
    0.2691
\end{bmatrix}
\end{align}

<p style="text-align:justify">Daraus erhält man dann die Matrix $V$:</p>

\begin{align}
V = 
\begin{bmatrix} 
    0.2891 &  0.3895  & -0.8744\\
    -0.0118 & 0.9149  & 0.4036\\
    0.9572 & -0.1063  & 0.2691
\end{bmatrix}
\end{align}

<p style="text-align:justify">Die zwei Spalten der Matrix $U$ kann man nun folgendermaßen berechnen:</p>

\begin{align}
u_i = \frac{1}{\sigma_i}Av_i
\end{align}

<p style="text-align:justify">Die erste Spalte ist also:</p>

\begin{align}
u_1 = \frac{1}{6.0854}
\begin{bmatrix} 
    2 &  1 & 5 \\
    0 & -2 & 3
\end{bmatrix}
\begin{bmatrix} 
    0.2891  \\
    -0.0118 \\
    0.9572
\end{bmatrix}=
\begin{bmatrix} 
    0.8796  \\
    0.4757 
\end{bmatrix}
\end{align}

<p style="text-align:justify">Die zweite Spalte ist also:</p>

\begin{align}
u_1 = \frac{1}{2.4429}
\begin{bmatrix} 
    2 &  1 & 5 \\
    0 & -2 & 3
\end{bmatrix}
\begin{bmatrix} 
    0.3895  \\
    0.9149
    -0.1063
\end{bmatrix}=
\begin{bmatrix} 
    0.4758  \\
    -0.8796 
\end{bmatrix}
\end{align}

<p style="text-align:justify">Daraus erhält man dann die Matrix $U$:</p>

\begin{align}
U = 
\begin{bmatrix} 
    0.8796 & 0.4758  \\
    0.4757 & -0.8796
\end{bmatrix}
\end{align}

<p style="text-align:justify">Somit lautet die Singulärwertzerlegung:</p>

\begin{align}
A = U * \Sigma * V^T
\end{align}

\begin{align}
A = 
\begin{bmatrix} 
    -0.8796 &  -0.4758 \\
    -0.4758 & 0.8796
\end{bmatrix} *
\begin{bmatrix} 
    6.0854 &  0 & 0 \\
    0 & 2.4429  & 0
\end{bmatrix} *
\begin{bmatrix} 
    -0.289 & 0.011 & -0.957  \\
    -0.39 & -0.915 & 0.106 \\
    -0.874 & 0.404 & 0.269
\end{bmatrix}
\end{align}


</font>

<h2>Code-Beispiel: Singulärwertzerlegung berechnen</h2>

In [39]:
import numpy as np

# Funktion zur Berechnung der Singulärwertzerlegung
def Singulaerwertzerlegung(A):
    
    # wenn Anzahl der Reihen kleiner als Anzahl der Spalten, berechne Eigenwerte mit AA^T und zuerst V
    if len(A) < len(A[0]):
        # Eigenwerte von AA^T berechnen
        AAT = A.dot(np.transpose(A))
        lamb, e = np.linalg.eig(AAT)
        # Eigenwerte sortieren (absteigend)
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # Sigma erstellen
        Sigma = np.zeros((len(A),len(A[0])))
        for i in range(len(A)):
            Sigma[i,i] = np.sqrt(lamb[i])
    
    
        # Eigenwerte von A^TA berechnen
        ATA = np.transpose(A).dot(A)
        lamb, e = np.linalg.eig(ATA)
    
        # Eigenwerte sortieren (absteigend)
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # V erstellen
        V = np.zeros((len(A[0]), len(A[0])))
        for i in range(len(A[0])):
            for j in range(len(A[0])):
                V[i][j] = e[i][j]
        
        # Berechnen von U
        U = np.zeros((len(A), len(A)))
        for i in range(len(A)):
            U[:,i] = np.divide(A.dot(V[:,i]),Sigma[i][i])
            
    else:
        # Eigenwerte von A^TA berechnen
        ATA = np.transpose(A).dot(A)
        lamb, e = np.linalg.eig(ATA)
        # Eigenwerte sortieren (absteigend)
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # Sigma erstellen
        Sigma = np.zeros((len(A),len(A[0])))
        for i in range(len(A[0])):
            Sigma[i,i] = np.sqrt(lamb[i])
    
    
        # Eigenwerte von AA^T berechnen
        AAT = A.dot(np.transpose(A))
        lamb, e = np.linalg.eig(AAT)
    
        # Eigenwerte sortieren (absteigend)
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # U erstellen
        U = np.zeros((len(A), len(A)))
        for i in range(len(A)):
            for j in range(len(A)):
                U[i][j] = e[i][j]
        
        # Berechnen von V
        V = np.zeros((len(A[0]), len(A[0])))
        for i in range(len(A[0])):
            V[:,i] = np.divide(np.transpose(A).dot(U[:,i]),Sigma[i][i])
    
    # Singulärwertzerlegung anzeigen
    print("U = ", U)
    print("Sigma = ", Sigma)
    print("V = ", V)
    print("A = ", U.dot(Sigma.dot(np.transpose(V))))

In [40]:
# Eingabe-Matrix, kann beliebig geändert werden
#A = np.array([[1, 1],
#    [0, 1]])

A = np.array([[2, 1, 5],
    [0, -2, 3], [2, 3, 4], [4, 3, 2]])

Singulaerwertzerlegung(A)

U =  [[-0.58526771 -0.37290509 -0.01377053 -0.71987073]
 [-0.16650093 -0.74568816  0.38965598  0.51419338]
 [-0.59003749  0.0904194  -0.6671508   0.44563426]
 [-0.53065516  0.54471579  0.6347349   0.13711823]]
Sigma =  [[8.94196943 0.         0.        ]
 [0.         4.3328427  0.        ]
 [0.         0.         1.50587413]
 [0.         0.         0.        ]]
V =  [[-0.50025121  0.37247874  0.78167021]
 [-0.40419998  0.69789674 -0.59123812]
 [-0.76574872 -0.61171867 -0.19856779]]
A =  [[ 2.00000000e+00  1.00000000e+00  5.00000000e+00]
 [-6.10622664e-16 -2.00000000e+00  3.00000000e+00]
 [ 2.00000000e+00  3.00000000e+00  4.00000000e+00]
 [ 4.00000000e+00  3.00000000e+00  2.00000000e+00]]
